### ISSUE TITLE
[add-security-headers] allow customizable csp header

### ISSUE THREAD

**Issue by zxkane** [awslabs/aws-cloudfront-extensions#138]
For different website, we have different content security policies, for example, we need add the whitelist for some content.

https://github.com/awslabs/aws-cloudfront-extensions/blob/1a0dc02bbd7b36944360b5739f768c62fe43f15c/edge/nodejs/add-security-headers/add-security-headers/app.js#L20

It’s would be more useful for allowing customizing the csp header.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by NingLu** [comment]
Hi zxkane@, 

The issue has been fixed in https://github.com/awslabs/aws-cloudfront-extensions/commit/ea8f73d40f5a28fd6191f52b7b1b404d9340d2f7 

Production test has been passed as well

As for how to add parameters, need to use double quote instead of single quote, if you want to use single quote, need to add "\\" before the single quote, here're two options

- default-src \\'none\\';
- default-src "none";

Please be aware that only use single quote will fail, such as default-src 'none', because we use single quote in UpdateEdgeCodeFunction to update the parameters

As for how to add parameters in SAR by CDK, here's the reference https://github.com/pahud/cdk-cloudfront-plus/blob/main/src/extensions.ts#L184
